name: Publish Extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  release:
    types:
    - created

jobs:
  deploy:
    name: deploy extension
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - run: npm install
    - name: Publish
      if: success() && startsWith(github.ref, 'refs/tags/') 
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
